package com.elt.constants;

public enum CallType {
	ADMIN_LOGIN_SERVICE, EMPLOYEE_LOGIN_SERVICE, ADMIN_ADD_HOLIDAY_SERVICE, GET_HOLIDAY_RECORD_GRID_INFO,
	DELETE_ALL_HOLIDAY_RECORD_SERVICE, SAVE_CURRENT_YEAR_RECORD_SERVICE, GET_CURRENT_YEAR_RECORD_SERVICE,
	EMPLOYEE_REGISTER_SERVICE, GET_ALL_EMPLOYEES_SERVICE, MARK_OR_UNMARK_EMPLOYEE_AS_MANAGER, VALIDATE_EMPLOYEE,
	GET_ALL_LEAVE_COUNTS, APPLY_LEAVE, GET_EMPLOYEE_LEAVE_GRID_INFO, CANCEL_EMPLOYEE_LEAVE,
	GET_CURRENT_LOGIN_EMP_DETAILS, GET_EMPLOYEE_WISE_LEAVE_REQUEST, APPROVE_LEAVE_OF_EMPLOYEE, CANCEL_LEAVE_OF_EMPLOYEE,
	GET_MANAGER_RECORD, GET_MANAGER_LEAVE_GRID_INFO
}
